### ISSUE TITLE
Sometimes Spotify won't start until you run it on your phone

### ISSUE THREAD

**Issue by unlive74** [hufman/AndroidAutoIdrive#329]
Sometimes (in about 20% of connections) Spotify won't start until you run it on your phone. Just an empty window instead of an artist and a song. I think in my log the manual start of Spotify is 18:15:12.

[logcat_06-23-2021_18-15-17.zip](https://github.com/hufman/AndroidAutoIdrive/files/6702213/logcat_06-23-2021_18-15-17.zip)

**Comment by hufman** [comment]
I appreciate your good taste in music.

I found these exceptions:
```
[06-23 18:10:26.888 4834:19229 E/Spotify]
[OkHttp https://login5.spotify.com/...] Exception on getting result data
java.io.IOException: Canceled
	at udk.intercept(SourceFile:36)
	at rdk.g(SourceFile:9)
	at rdk.f(SourceFile:1)
	at okhttp3.z.c(SourceFile:23)
	at okhttp3.z$b.a(SourceFile:2)
	at cdk.run(SourceFile:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

[06-23 18:10:26.898 4834:19227 E/Spotify]
[OkHttp https://apresolve.spotify.com/...] Exception on getting result data
java.io.IOException: Canceled
	at udk.intercept(SourceFile:36)
	at rdk.g(SourceFile:9)
	at rdk.f(SourceFile:1)
	at okhttp3.z.c(SourceFile:23)
	at okhttp3.z$b.a(SourceFile:2)
	at cdk.run(SourceFile:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

[06-23 18:10:54.537 9135:9135 E/SpotifyAppController]
Failed to connect to Spotify Remote: com.spotify.protocol.error.SpotifyAppRemoteException: Result was not delivered on time.
```
which seem to tell me that Spotify itself couldn't connect to the internet to validate the app's login attempt. My theory is that it sometimes works and caches the result for a day or so, and then sometimes the internet is not available when it needs to refresh the login session and this error happens.
Without this login session, the app is unable to start Spotify directly, though Spotify's Media Session becomes available for control after you start it manually. I suspect it may not have Browse or Now Playing access in this state. It may be the case that you can go to the app list and try clicking it again, or selecting a different app and back to Spotify, to get it to reconnect while actively driving.
